In [ ]:
import numpy as np

# Creating Vector & Matrix

In [ ]:
# Creating a vector
vector = np.array([1, 2, 3])
print("Vector:")
print(vector)
print()

# Creating a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:")
print(matrix)
print()

Vector:
[1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]]



# Accessing elements 

In [ ]:
# Accessing elements of a vector
print("Accessing elements of the vector:")
print("First element:", vector[0])
print("Second element:", vector[1])
print("Last element:", vector[-1])
print()

# Accessing elements of a matrix
print("Accessing elements of the matrix:")
print("Element at row 0, column 1:", matrix[0, 1])
print("Element at row 1, column 2:", matrix[1, 2])
print()

Accessing elements of the vector:
First element: 1
Second element: 2
Last element: 3

Accessing elements of the matrix:
Element at row 0, column 1: 2
Element at row 1, column 2: 6



# Performing operations on vectors

In [26]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [27]:
# Vector addition
addition = v1 + v2
print("Vector Addition:")
print(addition)
print()

Vector Addition:
[5 7 9]



In [28]:
# Vector multiplication by a scalar
scalar_multiplication = 2 * v1
print("Vector Scalar Multiplication:")
print(scalar_multiplication)
print()

Vector Scalar Multiplication:
[2 4 6]



In [29]:
# Dot product of two vectors
dot_product = np.dot(v1, v2) # (a*A) + (b*B) + (c*C)
print("Vector Dot Product:")
print(dot_product)
print()

Vector Dot Product:
32



In [30]:
# Computing the cross product
cross_product = np.cross(v1, v2)

print("Cross Product:")
print(cross_product)

Cross Product:
[-3  6 -3]


# Performing operations on matrices

- Matrix addition using np.add().
- Matrix subtraction using np.subtract().
- Element-wise matrix multiplication using np.multiply().
- Matrix multiplication (dot product) using np.dot().
- Matrix transpose using np.transpose().
- Determinant of a matrix using np.linalg.det().
- Eigenvalues and eigenvectors of a matrix using np.linalg.eig().

In [ ]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [ ]:
# Matrix addition
addition = np.add(matrix1, matrix2)
print("Matrix Addition:")
print(addition)
print()

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]



In [ ]:
# Matrix subtraction
subtraction = np.subtract(matrix1, matrix2)
print("Matrix Subtraction:")
print(subtraction)
print()

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]



In [ ]:
# Matrix mul
mul = m1 * m2
print("Matrix mul:")
print(mul)
print()

Matrix mul:
[[ 5 12]
 [21 32]]



In [ ]:
# Matrix multiplication (element-wise)
elementwise_multiplication = np.multiply(matrix1, matrix2)
print("Element-wise Matrix Multiplication:")
print(elementwise_multiplication)
print()

Element-wise Matrix Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]



In [ ]:
# Matrix multiplication (dot product)
dot_product = np.dot(matrix1, matrix2)
print("Matrix Dot Product:")
print(dot_product)
print()

Matrix Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]



In [ ]:
# Matrix transpose
transpose = np.transpose(matrix1)
print("Matrix Transpose:")
print(transpose)
print()

Matrix Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]



In [ ]:
# Determinant of a matrix
determinant = np.linalg.det(matrix1)
print("Matrix Determinant:")
print(determinant)
print()

Matrix Determinant:
0.0



In [ ]:
# Eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("Matrix Eigenvalues:")
print(eigenvalues)
print("Matrix Eigenvectors:")
print(eigenvectors)

Matrix Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Matrix Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
